Repository fack2/Hebron-must-see, pull requests merged in 2019-09, with the labels that each got.

#39 react router setup is done
  client/package.json
  client/src/App.js
  client/src/components/Start/index.js
  client/src/components/Start/style.css
Labels: awaiting-review

#43 related #24 filter is done as a component
  client/src/App.js
  client/src/components/Filter/index.js
  client/src/components/Filter/style.css
  client/src/components/Guides/index.js
  client/src/components/Places/index.js
  client/src/components/Places/style.css
  client/src/components/Start/index.js
  client/src/components/Start/style.css
Labels: awaiting-review

#51 Navbar-menu related to #28
  client/src/App.js
  client/src/assets/logo.png
  client/src/components/SharedComponents/navbar/index.js
  client/src/components/SharedComponents/navbar/navbar.css
Labels: awaiting-review, changes-requested

#42 Login and protected routes in backend
  client/.env
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Filter/index.js
  client/src/components/Guides/index.js
  client/src/components/OnePlace/index.js
  client/src/components/Places/index.js
  client/src/components/SharedComponents/Login/index.js
  client/src/components/SharedComponents/Login/style.css
  client/src/components/Start/index.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/Guides.js
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/places.js
  server/database/dbBuild.js
  server/database/queries/getPassword.js
  server/database/queries/places.js
  server/middleware/auth.js
Labels: changes-requested

#55 create arabic list words page related with #23
  client/src/App.js
  client/src/components/arabicListWords/index.js
  client/src/components/arabicListWords/style.css
  server/controllers/Guides.js
  server/controllers/arabicList.js
  server/controllers/index.js
  server/database/queries/getArabicWords.js
Labels: changes-requested

#54 #27 One place
  client/src/App.css
  client/src/App.js
  client/src/components/Guides/index.js
  client/src/components/ListOfItems/index.js
  client/src/components/ListOfItems/style.css
  client/src/components/OnePlace/index.js
  client/src/components/OnePlace/style.css
  client/src/components/SharedComponents/navbar/index.js
  client/src/components/SharedComponents/navbar/navbar.css
  server/controllers/guides.js
  server/controllers/index.js
  server/database/queries/guidesAndUsers.js
Labels: changes-requested

#44 Signup component related to #20
  client/src/App.js
  client/src/components/SharedComponents/Signup/index.js
  client/src/components/SharedComponents/Signup/signup.css
  server/controllers/index.js
  server/controllers/signup.js
  server/database/queries/addGuide.js
  server/database/queries/addUser.js
Labels: changes-requested

#64 Words pronunciation
  client/src/components/Filter/style.css
  client/src/components/Guides/index.js
  client/src/components/OnePlace/index.js
  client/src/components/Places/index.js
  client/src/components/SharedComponents/Login/index.js
  client/src/components/SharedComponents/Login/style.css
  client/src/components/arabicListWords/index.js
  client/src/components/arabicListWords/style.css
  package-lock.json
  package.json
  server/controllers/arabicListPronunciation.js
  server/controllers/index.js
Labels: approved
